apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-flex-kv-podid
    aadpodidbinding: "podbindingselector"
  name: nginx-flex-kv-podid
spec:
  containers:
  - name: nginx-flex-kv-podid
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /kvmnt
      readOnly: true
  volumes:
  - name: test
    flexVolume:
      driver: "azure/kv"
      options:
        usepodidentity: "true"                    # [OPTIONAL] if not provided, will default to "false"
        keyvaultname: "..."                       # [REQUIRED] the name of the KeyVault
        keyvaultobjectnames: "test-secret"        # [REQUIRED] list of KeyVault object names (semi-colon separated)
        keyvaultobjecttypes: secret               # [REQUIRED] list of KeyVault object types: secret, key, cert
        resourcegroup: "..."                      # [REQUIRED] the resource group of the KeyVault
        subscriptionid: "..."                     # [REQUIRED] the subscription ID of the KeyVault
        tenantid: "..."                           # [REQUIRED] the tenant ID of the KeyVault