apiVersion: v1
kind: Pod
metadata:
  name: nginx-configmaps-and-secrets
spec:
  containers:
  - name: nginx-configmaps-and-secrets
    image: nginx
    volumeMounts:
      - name: file-configmap
        subPath: file.text
        mountPath: /filemount/file.text
    env:
    - name: SINGLE_ENV_SECRET
      valueFrom:
        secretKeyRef:
          name: env-secret
          key: SINGLE_ENV_SECRET_KEY
    envFrom:
      - secretRef:
          name: terraform-secret
      - configMapRef:
          name: env-configmap
  volumes:
    - name: file-configmap
      configMap:
        name: file-configmap