# This is the alert manager configuration, it needs to be a secret, and the config itself can be read using https://www.base64decode.org/
# Alertmanager instances require the secret resource naming to follow the format alertmanager-{ALERTMANAGER_NAME} (check https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/alerting.md)
apiVersion: v1
data:
  alertmanager.yaml: CONFIGURATION_AS_ENCODED_SECRET
kind: Secret
metadata:
  name: alertmanager-coreops-alertmanager
  namespace: coreops-monitoring-alertmanager
type: Opaque