##---
# Source: Example-Application/charts/Frontend/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: pitt3
  labels:
    heritage: Tiller
    release: example-application-release
    chart: Frontend-1.0.0
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      namespace: pitt3
    spec:
      restartPolicy: Always
      containers:
        - name: frontend-container
          image: akswsweuacr.azurecr.io/workshop/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: COLOR
              value: blue
            - name: PORT
              value: "80"
            - name: BACKEND_BASEURL
              value: "http://localhost:8081"
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 1
          resources:
            requests:
              memory: "250Mi"
              cpu: "125m"
            limits:
              memory: "1000Mi"
              cpu: "250m"
