apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus-service
  namespace: kube-system
spec:
  selector:
    app: prometheus
    prometheus: prometheus
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090