apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: coreops-monitoring-cadvisor
  labels:
    k8s-app: cadvisor
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
    k8s-app: cadvisor
