apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  namespace: coreops-monitoring-kube-state-metrics
  labels:
    k8s-app: kube-state-metrics
spec:
  jobLabel: kube-state-metrics
  selector:
    matchLabels:
      k8s-app: kube-state-metrics
  namespaceSelector:
    matchNames:
    - coreops-monitoring-kube-state-metrics
  endpoints:
  - port: http-metrics
    interval: 15s
    honorLabels: true
