apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
    app: prometheus
  name: prometheus
  namespace: kube-system
spec:
  baseImage: quay.io/prometheus/prometheus
  nodeSelector:
    beta.kubernetes.io/os: linux
  replicas: 1
  retention: 15d
  alerting:
    alertmanagers:
    - namespace: coreops-monitoring-alertmanager
      name: coreops-alertmanager # name of the alert manager service, not the manager itself!
      port: web
  resources:
    requests:
      cpu: 70m
      memory: 500Mi
    limits:
      cpu: 350m
      memory: 1Gi
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {} # auto discover all service monitors accross all namespaces
  serviceMonitorSelector: {} # auto discover all service monitors in namespaces configured one line above
  ruleSelector:
    matchLabels:
      role: coreops-alertmanager-alert-rules
      prometheus: coreops-alertmanager
  version: v2.9.2