apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: coreops-alertmanager-alert-rules
    prometheus: coreops-alertmanager
  name: coreops-alertmanager-memory-alert
  namespace: kube-system
spec:
  groups:
  - name: coreops-cluster
    rules:
    - alert: ClusterMemoryAlert
      expr: 1 - ((sum(node_memory_MemAvailable_bytes)) / sum(node_memory_MemTotal_bytes)) > 0.5
      labels: 
        cluster: CLUSTER_NAME
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: coreops-alertmanager-alert-rules
    prometheus: coreops-alertmanager
  name: coreops-alertmanager-too-many-pods-alert
  namespace: kube-system
spec:
  groups:
  - name: coreops-cluster
    rules:
    - alert: ClusterTooManyPodsAlert
      expr: sum(kube_pod_container_status_running) > 44
      labels: 
        cluster: CLUSTER_NAME