apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: coreops-alertmanager
  name: coreops-alertmanager
  namespace: coreops-monitoring-alertmanager
spec:
  endpoints:
  - interval: 30s
    port: web
  selector:
    matchLabels:
      alertmanager: coreops-alertmanager